// <auto-generated />
using System;
using GitLogAnalysis.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GitLogAnalysis.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GitLogAnalysis.Core.Aggregates.GitAgg.Entities.ReleaseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_RELEASE")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FL_ACTIVE")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("AddedLines")
                        .HasColumnName("NR_ADDED_LINES")
                        .HasColumnType("int");

                    b.Property<int>("Authors")
                        .HasColumnName("NR_AUTHORS")
                        .HasColumnType("int");

                    b.Property<int>("Commits")
                        .HasColumnName("NR_COMMITS")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalDate")
                        .HasColumnName("DT_FINAL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InitialDate")
                        .HasColumnName("DT_INITIAL")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseName")
                        .HasColumnName("DS_RELEASE_NAME")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("RemovedLines")
                        .HasColumnName("NR_REMOVED_LINES")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_RELEASE_DATA");
                });
#pragma warning restore 612, 618
        }
    }
}
